import { db } from "../lib/db";
import * as schema from "../lib/db/schema";
import fs from "fs";

import { sql } from "drizzle-orm";

async function main() {
  const dataFile = fs.readFileSync("neon_data.json", "utf-8");
  
  // Custom reviver to parse ISO strings into Date objects
  const isoDateFormat = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})?$/;
  const data = JSON.parse(dataFile, (key, value) => {
    if (typeof value === "string" && isoDateFormat.test(value)) {
      return new Date(value);
    }
    return value;
  });

  const identityTables = [
    "member_snapshots", "membership_events", "wars", "war_attacks", 
    "capital_district_snapshots", "capital_raid_seasons", "war_rosters", 
    "war_roster_slots", "hall_of_fame_records", "cwl_seasons", "runtime_settings"
  ];

  console.log("Temporarily setting identity columns to GENERATED BY DEFAULT...");
  for (const table of identityTables) {
    await db.execute(sql.raw(`ALTER TABLE ${table} ALTER COLUMN id SET GENERATED BY DEFAULT;`));
  }
  
  // Insert tables in order of dependencies (no foreign keys should fail)
  if (data.runtimeSettings?.length > 0) await db.insert(schema.runtimeSettings).values(data.runtimeSettings).onConflictDoNothing();
  if (data.clans?.length > 0) await db.insert(schema.clans).values(data.clans).onConflictDoNothing();
  if (data.members?.length > 0) await db.insert(schema.members).values(data.members).onConflictDoNothing();
  if (data.memberSnapshots?.length > 0) await db.insert(schema.memberSnapshots).values(data.memberSnapshots).onConflictDoNothing();
  if (data.membershipEvents?.length > 0) await db.insert(schema.membershipEvents).values(data.membershipEvents).onConflictDoNothing();
  if (data.unitLevels?.length > 0) await db.insert(schema.unitLevels).values(data.unitLevels).onConflictDoNothing();
  if (data.wars?.length > 0) await db.insert(schema.wars).values(data.wars).onConflictDoNothing();
  if (data.warAttacks?.length > 0) await db.insert(schema.warAttacks).values(data.warAttacks).onConflictDoNothing();
  if (data.warParticipants?.length > 0) await db.insert(schema.warParticipants).values(data.warParticipants).onConflictDoNothing();
  if (data.capitalDistrictSnapshots?.length > 0) await db.insert(schema.capitalDistrictSnapshots).values(data.capitalDistrictSnapshots).onConflictDoNothing();
  if (data.capitalRaidSeasons?.length > 0) await db.insert(schema.capitalRaidSeasons).values(data.capitalRaidSeasons).onConflictDoNothing();
  if (data.capitalContributions?.length > 0) await db.insert(schema.capitalContributions).values(data.capitalContributions).onConflictDoNothing();
  if (data.warRosters?.length > 0) await db.insert(schema.warRosters).values(data.warRosters).onConflictDoNothing();
  if (data.warRosterSlots?.length > 0) await db.insert(schema.warRosterSlots).values(data.warRosterSlots).onConflictDoNothing();
  if (data.hallOfFameRecords?.length > 0) await db.insert(schema.hallOfFameRecords).values(data.hallOfFameRecords).onConflictDoNothing();
  if (data.cwlSeasons?.length > 0) await db.insert(schema.cwlSeasons).values(data.cwlSeasons).onConflictDoNothing();

  console.log("Restoring identity columns to GENERATED ALWAYS and updating sequences...");
  for (const table of identityTables) {
    await db.execute(sql.raw(`ALTER TABLE ${table} ALTER COLUMN id SET GENERATED ALWAYS;`));
    await db.execute(sql.raw(`SELECT setval(pg_get_serial_sequence('${table}', 'id'), COALESCE((SELECT MAX(id) FROM ${table}), 1), true);`));
  }

  console.log("Successfully restored all data from neon_data.json");
  process.exit(0);
}

main().catch((err) => {
  console.error("Error restoring data:", err);
  process.exit(1);
});
